### ISSUE TITLE
splicing elements into an empty array

### ISSUE THREAD

**Issue by rlidwka** [invertase/denque#11]
Trying to add multiple elements to the array. Found that splice doesn't work there:

```js
var a;

a = new (require('denque'))([])
a.splice(0,0, 1,2,3,4,5)
console.log(a.toArray())
// []

a = []
a.splice(0,0, 1,2,3,4,5)
console.log(a)
// [ 1, 2, 3, 4, 5 ]
```

Splice stops on [this](https://github.com/invertase/denque/blob/212e59ee1d6f6ea2b03dbe38643e52a74e9d91c4/index.js#L296) empty array check.

**Comment by Salakar** [comment]
@rlidwka ah ye I see the issue, thanks for reporting it - will push a fix + tests for it in the next day or so.
