### ISSUE TITLE
.remove() fail to delete items when index < 0

### ISSUE THREAD

**Issue by lrills** [invertase/denque#21]
Version: 1.4.0

Though it's not referenced on document, but nagative index seem to be supported according to:
https://github.com/invertase/denque/blob/2a4fb0bc1bef9d84c4b6f2d460c140a776f03ae5/index.js#L215

Minimum steps to reproduce:

```js
q = new Denque()
q.push(1) // 1
q.push(2) // 2
q.push(3) // 3
q.remove(-2,2) // [ 2, 3 ]

q.length // 3
```

**Comment by Salakar** [comment]
Forgot to reply here sorry, this is fixed and published to npm under version 1.4.1 now. Thanks.
