### ISSUE TITLE
What's the point?

### ISSUE THREAD

**Issue by aimnadze** [invertase/denque#26]
Forgive me for my ignorance. But can you please enlighten me why such a data structure is needed in JavaScript? Isn't the native Array object capable of handling all such stuff?

Thanks in advance

**Comment by Salakar** [comment]
Arrays take linear O(N) time to do shift and unshift operations. That means in theory that an array with 1000 items is 1000x slower to do those operations than a deque with 1000 items. 10000x slower with 10000 items and so on.

Whereas on a double ended queue every queue operation is done in constant O(1) time.

**Comment by Ehesp** [comment]
Just to add, if you're doing basic operations with arrays don't worry about using this library. It's designed for high usage and throughput where performance is critical.

**Comment by aimnadze** [comment]
I got the idea. Thank you.
