### ISSUE TITLE
Support For Deno

### ISSUE THREAD

**Issue by Skillz4Killz** [invertase/denque#28]
Hello 👋 

Please, would you consider allowing denque to support Deno. After taking a look at the code I believe it should work as is without modifications. It would just help a lot, if it was available through https://deno.land/x there is an `add module` button near the bottom where you can set it up and it would automatically deploy on releases so you would never need to think about it again.

Use Case: I am currently working on a port of MongoDB nodejs driver to deno and parts of it use denque. I was hoping to be able to use it.

Thank You 😄

**Comment by Ehesp** [comment]
@Skillz4Killz Hey, just added it:

![image](https://user-images.githubusercontent.com/842078/103530586-97d40600-4e7f-11eb-9bda-e0c7924858de.png)

Let me know if anything else needs doing

**Comment by Skillz4Killz** [comment]
Awesome!

If i'm not mistaken, the module may have been reserved so it appears on the list but the files were not uploaded. The files get uploaded the next time a release or a tag is created on the repo if the webhook setup was completed.

**Comment by Ehesp** [comment]
Ah ok, I'll get a tag triggered.

**Comment by Salakar** [comment]
Done: https://deno.land/x/denque@v1.5.0

**Comment by jimmywarting** [comment]
Dose it not have to be esm?
