### ISSUE TITLE
Invalid TypeScript definition for .size()

### ISSUE THREAD

**Issue by paya-cz** [invertase/denque#37]
The `.size()` is defined as:

https://github.com/invertase/denque/blob/b6738e6e5db4a2d335eb44a1403b586db041e0c2/index.d.ts#L36

Shouldn't it return a `number`?

https://github.com/invertase/denque/blob/b6738e6e5db4a2d335eb44a1403b586db041e0c2/index.js#L94-L98

**Comment by Ehesp** [comment]
Fixed https://github.com/invertase/denque/commit/88c89a0957a817c3b3aefd50a90b119d656db3da
